# File: .readthedocs.yaml

version: 2

sphinx:
  builder: html
  configuration: docs/documentation/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/documentation/requirements.txt

# Build PDF & ePub
formats:
    - htmlzip
    - epub
    - pdf
