# File: docs/environment.yaml

name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==4.1.2
  - nbsphinx==0.8.1
  - pip:
    - sphinx_rtd_theme==0.5.2
    - myst_parser==0.15.1
    - sphinxcontrib.bibtex==2.3.0
